apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: lab1e1
spec:
  collectors:
    - logs:
        selector:
          - app=nginx
        namespace: '{{repl Namespace }}'
  analyzers: []

