apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: lab1e3
spec:
  collectors:
    - logs:
        selector:
          - app=nginx
        namespace: '{{repl Namespace }}'
  analyzers: [] # dex add answer from l1e2

