apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <!doctype html>
    <html lang="en">
    <head>
      <meta charset="utf-8">
      <title>Lab 1.2</title>
    </head>
    <body>
      <h2>Congrats!</h2>
      If you can read this, you're done fixing the instance for Lab 1.2, but there's still more to do!
      <br><br>
      Please return to the guide for Lab 1.2 and ensure you complete the exercise, adding a support analyzer to
      simplify debugging in the future, before proceeding to Lab 1.3.
    </body>
    </html>